server:
  port: 7001

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xueyou2000/cloud-config
  rabbitmq:
    host: 172.23.160.148
    port: 5672
    username: root
    password: 123456
    virtual-host: my_vhost


management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh